CREATE TABLE IF NOT EXISTS NEWS_TOPIC_OF_THE_SEASONS (
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    deleted_at TIMESTAMP DEFAULT NULL,
    news_id INTEGER NOT NULL,
    topic_of_the_season_id INTEGER NOT NULL,
    PRIMARY KEY (news_id, topic_of_the_season_id),
    FOREIGN KEY (news_id) REFERENCES NEWS(id) ON DELETE CASCADE,
    FOREIGN KEY (topic_of_the_season_id) REFERENCES TOPIC_OF_THE_SEASONS(id) ON DELETE CASCADE
);
