CREATE TYPE USER_ROLE AS ENUM ('admin', 'editor', 'regular');
CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    role USER_ROLE NOT NULL DEFAULT 'regular'
);