CREATE TABLE IF NOT EXISTS CONTACTS (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    deleted_at TIMESTAMP DEFAULT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    linkedin VARCHAR(255),
    github VARCHAR(255),
    active bool NOT NULL
);

CREATE UNIQUE INDEX unique_active_contact ON CONTACTS (active)
WHERE active = true;
