DROP INDEX IF EXISTS idx_finance_projects_group_id;
DROP INDEX IF EXISTS idx_tech_projects_group_id;
DROP INDEX IF EXISTS idx_game_projects_group_id;

DROP TABLE IF EXISTS FINANCE_REPOSITORIES;
DROP TABLE IF EXISTS TECH_REPOSITORIES;
DROP TABLE IF EXISTS GAME_REPOSITORIES;
DROP TABLE IF EXISTS GAMES_PLAYED;
DROP TABLE IF EXISTS PROJECT_GROUPS;
DROP TABLE IF EXISTS CONTACTS;

DROP TYPE IF EXISTS GAME_GENRES;
DROP TYPE IF EXISTS PROJECT_TYPE;
